### ISSUE TITLE
Trouble installing: No module named 'space_escape.scenes.game'

### ISSUE THREAD

**Issue by lephe** [Raksoiv/space-escape#1]
So this is probably a problem with the installation step. I first ran the basic combo of `setup.py build` then `setup.py install --home ~/.local` (installing to system directory produced the same problem). This gave me a shiny `space-escape` executable, but this happens:

```
% space-escape
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
(...)
  File "/home/el/.local/lib/python/space_escape_raksoiv-0.1.0-py3.8.egg/space_escape/scenes/__init__.py", line 2, in <module>
    from .game.game import Game
ModuleNotFoundError: No module named 'space_escape.scenes.game'
```

I *can* run the game from the main folder with `PYTHONPATH="." python3 space_escape/main.py`. I suppose a few installation instructions in the README would help. ^^

**Comment by Raksoiv** [comment]
@lephe effectively there was an issue that involves a missing init file in the base folder of the game scene, thanks for pointing out, the las commit [dbdde0c](https://github.com/Raksoiv/space-escape/commit/dbdde0cd08203096198c2e3ac649f3e3f840091f) should fix it. Give me you feedback when you can.

Thanks again

**Comment by lephe** [comment]
Works just fine now! Thank you very much.
